id: P005559
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W15562
  title: བ་རི་བེའུ་བུམ།
  author: ''
  volumes:
    24b84e4faf654e178ef937d7ffc753c2:
      image_group_id: I5279
      title: ''
      volume_number: 1
      total_pages: 590
      base_file: v001.txt
