id: I881745D0
legacy_id: P005559
ocr_import_info:
  bdrc_scan_id: W15562
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:16:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:46:51.964542+00:00'
last_modified: 2022-08-30 22:47:16.888370
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W15562
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW15562
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བ་རི་བེའུ་བུམ།
  author: བ་རི་ལོ་ཙཱ་བ་རིན་ཆེན་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.7190331918265935
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I5279:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5279
      total_pages: 590
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5279.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7190331918265935
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
